gle.freq-dawg:	gle.freq-text gle.unicharset
	wordlist2dawg gle.freq-text gle.freq-dawg gle.unicharset

gle-uncial.freq-dawg:	gle-uncial.freq-text gle-uncial.unicharset
	wordlist2dawg gle-uncial.freq-text gle-uncial.freq-dawg gle-uncial.unicharset
	
gle-uncial.word-dawg:	gle-uncial.word-text gle-uncial.unicharset
	wordlist2dawg gle-uncial.word-text gle-uncial.word-dawg gle-uncial.unicharset

