gle.freq-dawg:	gle.freq-text
	wordlist2dawg gle.freq-text gle.freq-dawg gle.unicharset

# Commented, until I have a unicharset	
#gle-uncial.freq-dawg:	gle-uncial.freq-text
#	wordlist2dawg gle-uncial.freq-text gle-uncial.freq-dawg gle-uncial.unicharset
	
