gle.freq-dawg:	gle.freq-text
	wordlist2dawg gle.freq-text gle.freq-dawg

gle-uncial.freq-dawg:	gle-uncial.freq-text
	wordlist2dawg gle-uncial.freq-text gle-uncial.freq-dawg
	
gle-uncial.word-dawg:	gle-uncial.word-text
	wordlist2dawg gle-uncial.word-text gle-uncial.word-dawg
